import type { MetadataRoute } from "next";
import { siteConfig } from "@/lib/site";

export const dynamic = "force-static";

const routes = [
  "",
  "/about",
  "/ai-automation",
  "/contact",
  "/insights",
  "/portfolio",
  "/portfolio/ai-content-publisher",
  "/portfolio/ai-user-activity-plugin",
  "/portfolio/ai-video-ad-generation",
  "/portfolio/australian-travel-data-mining",
  "/portfolio/aux-mobile-app",
  "/portfolio/beauty-stories",
  "/portfolio/brp-truck-advertising",
  "/portfolio/car-washing-security",
  "/portfolio/cfmoto-kyiv",
  "/portfolio/consolegroup",
  "/portfolio/cv-processing",
  "/portfolio/dzikus-media-app",
  "/portfolio/dzvinski",
  "/portfolio/eboss-recruitment-crm",
  "/portfolio/eleve-design-website",
  "/portfolio/fidan-construction",
  "/portfolio/green-agro",
  "/portfolio/hide-seek-chrome-extension",
  "/portfolio/iamqr",
  "/portfolio/linkedin-data-scraping",
  "/portfolio/neon-vibez",
  "/portfolio/restaurant-menu-design",
  "/portfolio/shopify-loyalty-plugin",
  "/portfolio/shopklub",
  "/portfolio/talent-connect",
  "/portfolio/tamar-film-website",
  "/portfolio/telegram-shopify-integration",
  "/portfolio/the-wow-camp-website",
  "/portfolio/whatsapp-chatbox-integration",
  "/portfolio/zahid-power-motors",
  "/privacy",
  "/services",
  "/services/advertisement-creation",
  "/services/ai-automation",
  "/services/ai-integration",
  "/services/cybersecurity",
  "/services/data-migration",
  "/services/data-mining",
  "/services/design",
  "/services/ecommerce",
  "/services/google-ads",
  "/services/mobile-app-development",
  "/services/news",
  "/services/small-business-it",
  "/services/universal-plugin-solutions",
  "/services/website-development",
  "/services/website-seo",
  "/terms",
  "/testimonials",
] as const;

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((route) => ({ url: `${siteConfig.url}${route}` }));
}
